openapi: 3.0.0
info:
  title: New Collection
  version: 1.0.0-oas3
servers:
  - url: http://127.0.0.1:5050
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /image:
    get:
      tags:
        - default
      summary: Get Image
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    
  /login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: akkhilsp543
                password: asp12345
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /refresh:
    post:
      tags:
        - default
      summary: Refresh User Token
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /dummy:
    get:
      tags:
        - default
      summary: All Users
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user:
    get:
      tags:
        - default
      summary: User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: Update User Details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Akhil
                email: ak@em.ail
                image: postbe8a35ad6412610914195
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /password/reset:
    put:
      tags:
        - default
      summary: Update Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                new_password: akhil123
                old_password: akhil123
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /follow:
    post:
      tags:
        - default
      summary: Follow User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                following: rjc
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /following:
    get:
      tags:
        - default
      summary: Following
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /followers:
    get:
      tags:
        - default
      summary: Followers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /blog:
    get:
      tags:
        - default
      summary: Blog
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: First
                content:
                  type: string
                  example: First Post through Postman
                image:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: Blog
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                title: First Post
                content: fist post on postman
                image: post176a3e0a75c01c0956247
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Blog
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /public:
    get:
      tags:
        - default
      summary: Public Feed
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/feed:
    get:
      tags:
        - default
      summary: User Feed
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/akkhilsp543:
    get:
      tags:
        - default
      summary: User Public
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}